# Generated by Django 4.2.13 on 2024-06-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-update', '-created']},
        ),
    ]
